version: '3'

services:
    postgres:
        image: postgres:13-alpine
        environment:
            POSTGRES_DB: data-server
            POSTGRES_PASSWORD: data-server
            POSTGRES_USER: data-server
        ports:
            - '5432:5432'
        volumes:
            - postgres:/var/lib/postgresql/data

volumes:
    postgres:
